# Generated by Django 4.2 on 2025-12-02 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Entrez une adresse email valide', max_length=254, unique=True, verbose_name='Adresse Email')),
                ('company_name', models.CharField(help_text='Nom officiel de votre entreprise', max_length=255, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(blank=True, help_text="Adresse postale de l'entreprise", null=True, verbose_name='Adresse complète')),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone de contact', max_length=20, null=True, verbose_name='Téléphone')),
                ('tax_id', models.CharField(blank=True, help_text="Numéro d'identification fiscale", max_length=50, null=True, verbose_name='Numéro fiscal')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('FABRICANT', 'Fabricant'), ('TRANSPORT', 'Société de Transport'), ('ENTREPOT', 'Entrepôt'), ('MAGASIN', 'Magasin'), ('CLIENT', 'Client')], default='CLIENT', help_text="Rôle de l'utilisateur dans la chaîne d'approvisionnement", max_length=20, verbose_name='Rôle')),
                ('is_approved', models.BooleanField(default=False, help_text="Indique si le compte a été approuvé par l'administrateur", verbose_name='Compte approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Unique')),
                ('name', models.CharField(help_text='Nom commercial du produit', max_length=255, verbose_name='Nom du produit')),
                ('description', models.TextField(help_text='Description détaillée du produit', verbose_name='Description')),
                ('sku', models.CharField(help_text='Stock Keeping Unit - Référence unique du produit', max_length=100, unique=True, verbose_name='SKU')),
                ('batch_number', models.CharField(help_text='Numéro de lot de production', max_length=50, verbose_name='Numéro de lot')),
                ('production_date', models.DateField(help_text='Date de fabrication du produit', verbose_name='Date de production')),
                ('expiration_date', models.DateField(blank=True, help_text='Date de péremption si applicable', null=True, verbose_name="Date d'expiration")),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='Format: Longueur x Largeur x Hauteur (cm)', max_length=100, null=True, verbose_name='Dimensions')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix unitaire')),
                ('currency', models.CharField(choices=[('MAD', 'MAD'), ('EUR', 'EUR'), ('USD', 'USD')], default='MAD', max_length=3, verbose_name='Devise')),
                ('current_status', models.CharField(choices=[('CREATED', '🏭 Créé'), ('QUALITY_CHECK', '🔍 Contrôle qualité'), ('IN_TRANSIT', '🚚 En transit'), ('IN_WAREHOUSE', '📦 En entrepôt'), ('IN_STORE', '🏪 En magasin'), ('SOLD', '💰 Vendu'), ('RETURNED', '↩️ Retourné'), ('DESTROYED', '🗑️ Détruit')], default='CREATED', max_length=20, verbose_name='Statut actuel')),
                ('current_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation actuelle')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('blockchain_hash', models.CharField(blank=True, help_text='Dernier hash enregistré sur la blockchain', max_length=255, null=True, verbose_name='Hash Blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du contrat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('contract_address', models.CharField(help_text='Adresse du contrat sur la blockchain', max_length=255, unique=True, verbose_name='Adresse du contrat')),
                ('source_code', models.TextField(help_text='Code source du contrat intelligent', verbose_name='Code source')),
                ('abi', models.JSONField(help_text='Application Binary Interface du contrat', verbose_name='ABI')),
                ('status', models.CharField(choices=[('DRAFT', '📝 Brouillon'), ('DEPLOYED', '🚀 Déployé'), ('ACTIVE', '✅ Actif'), ('PAUSED', '⏸️ En pause'), ('TERMINATED', '🔚 Terminé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de déploiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Déployé par')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_contracts', to='traceability.product', verbose_name='Produit associé')),
            ],
            options={
                'verbose_name': 'Contrat Intelligent',
                'verbose_name_plural': 'Contrats Intelligents',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email utilisé pour la connexion', max_length=254, unique=True, verbose_name='Email de contact')),
                ('company_name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(help_text="Adresse complète de l'entreprise", verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro fiscal')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('FABRICANT', 'Fabricant'), ('TRANSPORT', 'Société de Transport'), ('ENTREPOT', 'Entrepôt'), ('MAGASIN', 'Magasin'), ('CLIENT', 'Client')], max_length=20, verbose_name='Rôle demandé')),
                ('message', models.TextField(blank=True, help_text="Message supplémentaire pour l'administrateur", null=True, verbose_name='Message')),
                ('status', models.CharField(choices=[('PENDING', '⏳ En attente'), ('APPROVED', '✅ Approuvé'), ('REJECTED', '❌ Rejeté'), ('CANCELLED', '🚫 Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('CREATION', '🏭 Création'), ('QUALITY_CHECK', '🔍 Contrôle qualité'), ('PACKAGING', '📦 Emballage'), ('TRANSPORT_START', '🚚 Début transport'), ('TRANSPORT_END', '✅ Fin transport'), ('WAREHOUSE_ENTRY', '📥 Entrée entrepôt'), ('WAREHOUSE_EXIT', '📤 Sortie entrepôt'), ('STORE_ENTRY', '🏪 Entrée magasin'), ('STORE_SHELF', '📋 Mise en rayon'), ('SALE', '💰 Vente'), ('RETURN', '↩️ Retour'), ('DESTRUCTION', '🗑️ Destruction'), ('OTHER', '📝 Autre')], max_length=20, verbose_name="Type d'étape")),
                ('location', models.CharField(help_text="Lieu où l'étape a été effectuée", max_length=255, verbose_name='Localisation')),
                ('gps_coordinates', models.CharField(blank=True, help_text='Format: Latitude,Longitude', max_length=100, null=True, verbose_name='Coordonnées GPS')),
                ('details', models.JSONField(default=dict, help_text='Informations supplémentaires au format JSON', verbose_name='Détails')),
                ('photo', models.ImageField(blank=True, help_text="Photo de preuve de l'étape", null=True, upload_to='step_photos/', verbose_name='Photo')),
                ('document', models.FileField(blank=True, help_text='Document associé (bon de livraison, etc.)', null=True, upload_to='step_documents/', verbose_name='Document')),
                ('blockchain_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transaction Blockchain')),
                ('blockchain_hash', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hash Blockchain')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_steps', to=settings.AUTH_USER_MODEL, verbose_name='Acteur responsable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='traceability.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Étape du produit',
                'verbose_name_plural': 'Étapes des produits',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='traceability.productcategory', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='traceability.productcategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(limit_choices_to={'is_approved': True, 'role': 'FABRICANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='manufactured_products', to=settings.AUTH_USER_MODEL, verbose_name='Fabricant'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INFO', 'ℹ️ Information'), ('SUCCESS', '✅ Succès'), ('WARNING', '⚠️ Avertissement'), ('ERROR', '❌ Erreur'), ('APPROVAL', "👤 Demande d'approbation"), ('PRODUCT_UPDATE', '📦 Mise à jour produit')], default='INFO', max_length=20, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('target_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle cible')),
                ('target_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID cible')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(help_text='Hash unique de la transaction Stellar', max_length=255, unique=True, verbose_name='Hash de transaction')),
                ('stellar_account', models.CharField(help_text='Compte Stellar qui a signé la transaction', max_length=56, verbose_name='Compte Stellar')),
                ('memo', models.TextField(help_text='Données stockées dans le mémo de la transaction', verbose_name='Mémo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_records', to='traceability.product', verbose_name='Produit')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_records', to='traceability.productstep', verbose_name='Étape associée')),
            ],
            options={
                'verbose_name': 'Enregistrement Blockchain',
                'verbose_name_plural': 'Enregistrements Blockchain',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Mise à jour'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('APPROVE', 'Approbation'), ('REJECT', 'Rejet'), ('SCAN', 'Scan QR Code')], max_length=20, verbose_name="Type d'action")),
                ('model_name', models.CharField(help_text='Nom du modèle Django concerné', max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(help_text="ID de l'objet concerné", max_length=255, verbose_name="ID de l'objet")),
                ('details', models.JSONField(default=dict, help_text="Informations supplémentaires sur l'action", verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['status'], name='traceabilit_status_a6e1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['role'], name='traceabilit_role_c28c87_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['created_at'], name='traceabilit_created_56d80d_idx'),
        ),
        migrations.AddIndex(
            model_name='productstep',
            index=models.Index(fields=['product', 'timestamp'], name='traceabilit_product_524f91_idx'),
        ),
        migrations.AddIndex(
            model_name='productstep',
            index=models.Index(fields=['step_type'], name='traceabilit_step_ty_547684_idx'),
        ),
        migrations.AddIndex(
            model_name='productstep',
            index=models.Index(fields=['actor'], name='traceabilit_actor_i_a34e08_idx'),
        ),
        migrations.AddIndex(
            model_name='productstep',
            index=models.Index(fields=['timestamp'], name='traceabilit_timesta_cd3037_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='traceabilit_sku_17e3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['batch_number'], name='traceabilit_batch_n_3c39ab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_status'], name='traceabilit_current_ddfbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['manufacturer'], name='traceabilit_manufac_6a8460_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['production_date'], name='traceabilit_product_cfa60d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='traceabilit_recipie_460f03_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='traceabilit_created_cea72c_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainrecord',
            index=models.Index(fields=['transaction_hash'], name='traceabilit_transac_4a0ea5_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainrecord',
            index=models.Index(fields=['product', 'created_at'], name='traceabilit_product_3f1c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainrecord',
            index=models.Index(fields=['is_verified'], name='traceabilit_is_veri_9499e3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='traceabilit_user_id_384b06_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='traceabilit_action__5824b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='traceabilit_model_n_c22728_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='traceabilit_timesta_2cb9de_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='traceabilit_email_2bbd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='traceabilit_role_8229b5_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_approved'], name='traceabilit_is_appr_183ba3_idx'),
        ),
    ]
