# Generated by Django 4.2 on 2025-12-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('DZ', 'DZ'), ('EUR', 'EUR'), ('USD', 'USD')], default='DZ', max_length=3, verbose_name='Devise'),
        ),
    ]
