# Generated by Django 4.2 on 2025-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_alter_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
